# Generated by Django 3.0.4 on 2020-07-19 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_todo_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='size',
        ),
    ]
