# Generated by Django 3.0.4 on 2020-07-19 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_auto_20200719_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='basket',
            field=models.CharField(choices=[('Dark', 'Dark'), ('Ligth Soft', 'Ligth Soft'), ('Dark Soft', 'Dark Soft')], default='Ligth Soft', max_length=10),
        ),
        migrations.AlterField(
            model_name='todo',
            name='item_type',
            field=models.CharField(choices=[('Shirts', 'Shirts'), ('Pants', 'Pants'), ('Skirts', 'Skirts'), ('Dresses', 'Dresses'), ('Shoes', 'Shoes')], default='Shirts', max_length=7),
        ),
        migrations.AlterField(
            model_name='todo',
            name='size',
            field=models.CharField(choices=[('Small', 'Small'), ('Medium', 'Medium'), ('Large', 'Large')], default='Large', max_length=6),
        ),
    ]
