# Generated by Django 3.0.4 on 2020-07-20 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_auto_20200720_0023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='basket',
            field=models.CharField(max_length=10),
        ),
    ]
