# Generated by Django 3.0.4 on 2020-07-20 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0008_auto_20200720_0411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='basket',
            field=models.CharField(choices=[], default='Ligth Soft', max_length=10),
        ),
    ]
