# Generated by Django 3.0.4 on 2020-07-20 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0009_auto_20200720_0417'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='isImportant',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='todo',
            name='basket',
            field=models.CharField(choices=[('Dark', 'Dark'), ('Ligth Soft', 'Ligth Soft'), ('Dark Soft', 'Dark Soft')], default='Ligth Soft', max_length=10),
        ),
    ]
